name: price-tracker
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - psycopg2
  - python
  - bs4
  - aiohttp=3.9.5
  - alembic=1.13.1
  - anyio=4.4.0
  - attrs=23.2.0
  - blinker=1.8.2
  - certifi=2024.2.2
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cryptography=42.0.7
  - fastapi=0.100.0
  - greenlet=3.0.3
  - grpcio
  - gunicorn=22.0.0
  - idna=3.7
  - Jinja2=3.1.4
  - jsonschema=4.22.0
  - mkl-service=2.4.0
  - numpy=1.26.4
  - pandas=2.1.4
  - pydantic=2.3.0
  - PyYAML=6.0.1
  - SQLAlchemy
  - uvicorn=0.22.0
  - pip:
    - apache-airflow==2.9.1
    - apache-airflow-providers-common-io==1.3.1
    - apache-airflow-providers-common-sql==1.13.0
    - apache-airflow-providers-fab==1.1.0
    - apache-airflow-providers-ftp==3.9.0
    - apache-airflow-providers-http==4.11.0
    - apache-airflow-providers-imap==3.6.0
    - apache-airflow-providers-smtp==1.7.0
    - apache-airflow-providers-sqlite==3.8.0
    - apispec==6.6.1
    - flask==2.2.5
    - flask-appbuilder==4.4.1
    - flask-babel==2.0.0
    - flask-caching==2.3.0
    - flask-jwt-extended==4.6.0
    - flask-limiter==3.7.0
    - flask-login==0.6.3
    - flask-session==0.5.0
    - flask-sqlalchemy==2.5.1
    - flask-wtf==1.2.1
    - itsdangerous==2.2.0
    - requests==2.32.2
    - requests-toolbelt==1.0.0
    - rich==13.7.1
    - starlette==0.29.0
    - swagger-ui-bundle==0.0.2
    - tabulate==0.9.0
    - werkzeug==2.2.3
    - WTForms==3.1.2
    - python-dotenv
    - selenium==4.24.0
